name: GitHub Classroom Workflow
on:
  push:
    branches:
      - lab3_test
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      # TODO setup variant, service and port

      - name: Run API Tests
        timeout-minutes: 5
        run: |
          chmod +x ./scripts/test-script.sh
          ./scripts/test-script.sh
        env:
          VARIANT: v1
          SERVICE_NAME: bonus-service
          PORT_NUMBER: 8080

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v