name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: |
          docker-compose build postgres
          docker-compose build api_gateway
          docker-compose build flight_service
          docker-compose build privilege-service
          docker-compose build ticket_service

      - name: Run containers
        timeout-minutes: 10
        run: |
          docker-compose up -d api_gateway
          docker-compose up -d flight_service
          docker-compose up -d privilege-service
          docker-compose up -d ticket_service

          docker-compose logs api_gateway
          docker-compose logs flight_service
          docker-compose logs privilege-service
          docker-compose logs ticket_service
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: 1/postman/collection.json
          environment: 1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v